# permissions for end users to view dynamicroles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dynamicrole-viewer-role
rules:
- apiGroups:
  - rbac.redhatcop.redhat.io
  resources:
  - dynamicroles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rbac.redhatcop.redhat.io
  resources:
  - dynamicroles/status
  verbs:
  - get
