# permissions for end users to view dynamicclusterroles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dynamicclusterrole-viewer-role
rules:
- apiGroups:
  - rbac.redhatcop.redhat.io
  resources:
  - dynamicclusterroles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rbac.redhatcop.redhat.io
  resources:
  - dynamicclusterroles/status
  verbs:
  - get
