apiVersion: rbac.redhatcop.redhat.io/v1alpha1
kind: DynamicClusterRole
metadata:
  name: dynamicclusterrole-sample
spec:
  inherit:
    - name: cluster-admin
      kind: ClusterRole
  deny:
    - apiGroups:
        - "user.openshift.io"
      resources:
        - "*"
      verbs:
        - "*"
    - apiGroups:
        - "metrics.k8s.io"
      resources:
        - "*"
      verbs:
        - "*"
  allow:
    - apiGroups:
        - "metrics.k8s.io"
      resources:
        - "pods"
      verbs:
        - "*"